# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/only_u/Desktop/permanent/rs/drone/fs-prototype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/only_u/Desktop/permanent/rs/drone/fs-prototype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/only_u/Desktop/permanent/rs/drone/fs-prototype/CMakeFiles /home/only_u/Desktop/permanent/rs/drone/fs-prototype//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/only_u/Desktop/permanent/rs/drone/fs-prototype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fs_prototype

# Build rule for target.
fs_prototype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fs_prototype
.PHONY : fs_prototype

# fast build rule for target.
fs_prototype/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/build
.PHONY : fs_prototype/fast

#=============================================================================
# Target rules for targets named hello_test

# Build rule for target.
hello_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_test
.PHONY : hello_test

# fast build rule for target.
hello_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_test.dir/build.make CMakeFiles/hello_test.dir/build
.PHONY : hello_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/main.cpp.s
.PHONY : main.cpp.s

src/problem/game_board.o: src/problem/game_board.cpp.o
.PHONY : src/problem/game_board.o

# target to build an object file
src/problem/game_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/game_board.cpp.o
.PHONY : src/problem/game_board.cpp.o

src/problem/game_board.i: src/problem/game_board.cpp.i
.PHONY : src/problem/game_board.i

# target to preprocess a source file
src/problem/game_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/game_board.cpp.i
.PHONY : src/problem/game_board.cpp.i

src/problem/game_board.s: src/problem/game_board.cpp.s
.PHONY : src/problem/game_board.s

# target to generate assembly for a file
src/problem/game_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/game_board.cpp.s
.PHONY : src/problem/game_board.cpp.s

src/problem/heuristics.o: src/problem/heuristics.cpp.o
.PHONY : src/problem/heuristics.o

# target to build an object file
src/problem/heuristics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/heuristics.cpp.o
.PHONY : src/problem/heuristics.cpp.o

src/problem/heuristics.i: src/problem/heuristics.cpp.i
.PHONY : src/problem/heuristics.i

# target to preprocess a source file
src/problem/heuristics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/heuristics.cpp.i
.PHONY : src/problem/heuristics.cpp.i

src/problem/heuristics.s: src/problem/heuristics.cpp.s
.PHONY : src/problem/heuristics.s

# target to generate assembly for a file
src/problem/heuristics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/heuristics.cpp.s
.PHONY : src/problem/heuristics.cpp.s

src/problem/tsp_board.o: src/problem/tsp_board.cpp.o
.PHONY : src/problem/tsp_board.o

# target to build an object file
src/problem/tsp_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/tsp_board.cpp.o
.PHONY : src/problem/tsp_board.cpp.o

src/problem/tsp_board.i: src/problem/tsp_board.cpp.i
.PHONY : src/problem/tsp_board.i

# target to preprocess a source file
src/problem/tsp_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/tsp_board.cpp.i
.PHONY : src/problem/tsp_board.cpp.i

src/problem/tsp_board.s: src/problem/tsp_board.cpp.s
.PHONY : src/problem/tsp_board.s

# target to generate assembly for a file
src/problem/tsp_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/problem/tsp_board.cpp.s
.PHONY : src/problem/tsp_board.cpp.s

src/search/focal_search.o: src/search/focal_search.cpp.o
.PHONY : src/search/focal_search.o

# target to build an object file
src/search/focal_search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/search/focal_search.cpp.o
.PHONY : src/search/focal_search.cpp.o

src/search/focal_search.i: src/search/focal_search.cpp.i
.PHONY : src/search/focal_search.i

# target to preprocess a source file
src/search/focal_search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/search/focal_search.cpp.i
.PHONY : src/search/focal_search.cpp.i

src/search/focal_search.s: src/search/focal_search.cpp.s
.PHONY : src/search/focal_search.s

# target to generate assembly for a file
src/search/focal_search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fs_prototype.dir/build.make CMakeFiles/fs_prototype.dir/src/search/focal_search.cpp.s
.PHONY : src/search/focal_search.cpp.s

src/tests/hello_test.o: src/tests/hello_test.cc.o
.PHONY : src/tests/hello_test.o

# target to build an object file
src/tests/hello_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_test.dir/build.make CMakeFiles/hello_test.dir/src/tests/hello_test.cc.o
.PHONY : src/tests/hello_test.cc.o

src/tests/hello_test.i: src/tests/hello_test.cc.i
.PHONY : src/tests/hello_test.i

# target to preprocess a source file
src/tests/hello_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_test.dir/build.make CMakeFiles/hello_test.dir/src/tests/hello_test.cc.i
.PHONY : src/tests/hello_test.cc.i

src/tests/hello_test.s: src/tests/hello_test.cc.s
.PHONY : src/tests/hello_test.s

# target to generate assembly for a file
src/tests/hello_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_test.dir/build.make CMakeFiles/hello_test.dir/src/tests/hello_test.cc.s
.PHONY : src/tests/hello_test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... fs_prototype"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... hello_test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/problem/game_board.o"
	@echo "... src/problem/game_board.i"
	@echo "... src/problem/game_board.s"
	@echo "... src/problem/heuristics.o"
	@echo "... src/problem/heuristics.i"
	@echo "... src/problem/heuristics.s"
	@echo "... src/problem/tsp_board.o"
	@echo "... src/problem/tsp_board.i"
	@echo "... src/problem/tsp_board.s"
	@echo "... src/search/focal_search.o"
	@echo "... src/search/focal_search.i"
	@echo "... src/search/focal_search.s"
	@echo "... src/tests/hello_test.o"
	@echo "... src/tests/hello_test.i"
	@echo "... src/tests/hello_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

